fix: Set sufficient permissions for publish job
When running the upload to PyPI action, we ran into:

    Error:  Trusted publishing exchange failure:
    OpenID Connect token retrieval failed:  GitHub:  missing or
    insufficient OIDC token permissions, the
    ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variable was unset

    This generally indicates a workflow configuration error, such as
    insufficient permissions.  Make sure that your workflow has
    `id-token: write` configured at the job level, e.g.:

    ```yaml
    permissions:
      id-token: write
    ```